version: '2.6'

services:

   typesense:
     image: typesense/typesense:0.22.2
     environment:
       TYPESENSE_DATA_DIR: /data
       TYPESENSE_API_KEY: xyz
     volumes:
       - /tmp/typesense-server-data:/data
     ports:
       - 8108:8108
     restart: "no"
